---
- hosts: jenkins
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Kubernetes tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
